library(leaps)
library(ISLR)
#for glmnet: lasso model
library(glmnet)

#taking training data from file train_housing
Housing = read.csv('/home/mayank/Downloads/Kaggle/train_housing.csv')
drops = c('Alley','PoolQC','MiscFeature','Fence','FireplaceQu','Id','Utilities',"Condition2","HouseStyle","RoofMatl","Exterior1st","Exterior2nd","Heating","Electrical","GarageQual")
Housing = Housing[,!(names(Housing) %in% drops)]
#set LotFrontage to the mean of all the non null values
Housing[is.na(Housing$LotFrontage),'LotFrontage'] = mean(Housing[!is.na(Housing$LotFrontage),'LotFrontage'])

#taking testing data from file test_housing
Housing.test = read.csv('/home/mayank/Downloads/Kaggle/test_housing.csv')
Housing.test = Housing.test[,!(names(Housing.test) %in% drops)]
#set LotFrontage to the mean of all the non null values
Housing.test[is.na(Housing.test$LotFrontage),'LotFrontage'] = mean(Housing.test[!is.na(Housing.test$LotFrontage),'LotFrontage'])

#function to get column names of all the factor columns
getNullNonFactorNames = function(data){
  #getting names of all the factor variables
  factor.names = sapply(data, function(x)is.factor(x))
  factor.names = factor.names[which(factor.names==TRUE)]
  factor.names = names(factor.names)
  
  #getting names of all the variables which have null values
  null.names = sapply(colnames(data),function(x)(sum(is.na(data[,x]))>0))
  null.names = null.names[which(null.names==TRUE)]
  null.names = names(null.names)
  
  #getting all the null factor variables
  valid.names = null.names %in% factor.names
  factor.null.names = null.names[valid.names]
  
  #getting all the non factor null variables
  non.factor.null.names = null.names[!valid.names]
  
  #set null values with valid values
  data = setNullValues(data,factor.names,non.factor.null.names)
  
  #return data
  data
}

#function to set all null values in training and testing data
setNullValues = function(data,factor.names,non.factor.null.names){
  
  #get all the non factor variables
  non.factor.names = colnames(data) %in% factor.names
  
  #set null factor variables with none
  for (i in factor.names){
    data[,i] = as.character(data[,i])
    data[is.na(data[,i]),i] = "None"
  }
  
  #set null non factor variables with 0
  for (i in non.factor.null.names){
    data[is.na(data[,i]),i] = 0
  }
  
  #return as data frame
  data.frame(data)
}

#filling null values in training data
Housing = getNullNonFactorNames(Housing)
#filling null values in test data
Housing.test = getNullNonFactorNames(Housing.test)

#creating this column to create model.matrix on test data
Housing.test['SalePrice'] = 0

#Lasso Regression 
#as number of variables are more,here 76, best subset selection may not work

#set seed to 1 to get correct random sample
set.seed(1)

#in case to preform cross validation: in this code these two are not used 
train = sample(c(TRUE,FALSE),nrow(Housing),rep=TRUE)
test = (!train)

#model matrix for training data
x = model.matrix(SalePrice~.,data=Housing)
y = Housing$SalePrice

#model matrix for test data
x.test = model.matrix(SalePrice~.,data=Housing.test)
y.test = Housing.test$SalePrice

#these columns are generated by model.matrix for factor variables which have None values
#these are dropped as these factor columns were not present in training data
dropMatrixCols = c("MSZoningNone", "KitchenQualNone", "FunctionalNone", "SaleTypeNone")
x.test = x.test[,!(colnames(x.test) %in% dropMatrixCols)]

#to perform 10 fold cross validation for various lambdas
cv.out = cv.glmnet(x,y,alpha=1)

#choose the best lambda 
bestlam = cv.out$lambda.min

#fitting lasso model with best lambda
lasso.mod = glmnet(x,y,alpha=1,lambda=bestlam)

#printing coefficients associated with variables which are significant
predCoef = predict(lasso.mod,s=bestlam,type="coefficients")
print(predCoef)

#predict the output values
pred = predict(lasso.mod,s=bestlam,newx = x[test,])

#write to CSV file
write.csv(pred, file="/home/mayank/Downloads/Kaggle/Ames Housing/output.csv")

